compiler/natives/src/{runtime,sync}: Add stub for SetMutexProfileFraction, implement runtime_SemacquireMutex.
SetMutexProfileFraction was added in Go 1.8, and needs to be explicitly
added to "runtime" package in GopherJS, because GopherJS doesn't inherit
most of upstream .go files of "runtime" package.

Document that it's not supported at this time.

Implement runtime_SemacquireMutex with same code as runtime_Semacquire.

Fixes many build errors.

Fixes net/rpc/jsonrpc tests:

	$ gopherjs test net/rpc/jsonrpc

	/Users/Dmitri/Dropbox/Work/2013/GoLand/src/github.com/gopherjs/gopherjs/test.438174805:1414
	          throw new Error(msg);
	                ^
	Error: runtime error: native function not implemented: sync.runtime_SemacquireMutex
	    at $callDeferred (/Users/Dmitri/Dropbox/Work/2013/GoLand/src/github.com/gopherjs/gopherjs/test.438174805:1414:17)
	    at $panic (/Users/Dmitri/Dropbox/Work/2013/GoLand/src/github.com/gopherjs/gopherjs/test.438174805:1453:3)
	    at $throwRuntimeError (/Users/Dmitri/Dropbox/Work/2013/GoLand/src/github.com/gopherjs/gopherjs/runtime.go:31:4)
	    at $packages.sync.runtime_SemacquireMutex (/Users/Dmitri/Dropbox/Work/2013/GoLand/src/github.com/gopherjs/gopherjs/test.438174805:3109:3)
	    at $packages.sync.Mutex.ptr.Lock (/sync/mutex.go:87:5)
	    at $packages.net/rpc.Server.ptr.sendResponse (/net/rpc/server.go:365:3)
	    at $packages.net/rpc.service.ptr.call (/net/rpc/server.go:394:3)
	    at f (/Users/Dmitri/Dropbox/Work/2013/GoLand/src/github.com/gopherjs/gopherjs/test.438174805:52:21)
	    at $goroutine (/Users/Dmitri/Dropbox/Work/2013/GoLand/src/github.com/gopherjs/gopherjs/test.438174805:1473:19)
	    at Timeout.$runScheduled [as _onTimeout] (/Users/Dmitri/Dropbox/Work/2013/GoLand/src/github.com/gopherjs/gopherjs/test.438174805:1514:7)
	    at tryOnTimeout (timers.js:224:11)
	    at Timer.listOnTimeout (timers.js:198:5)
	FAIL	net/rpc/jsonrpc	1.813s