compiler/natives/src/internal/testenv: Override HasExec to say no for GOARCH=js.
We cannot run tests that do exec.Command when GOARCH=js. Instead of
disabling individual tests, update testenv.HasExec to say no.

TestMutexMisuse in sync package was one such test. It begins with:

	func TestMutexMisuse(t *testing.T) {
		testenv.MustHaveExec(t)

As a result of this change, it no longer runs and fixes the following
issue:

	$ gopherjs test sync
	--- FAIL: TestMutexMisuse (0.01s)

/Users/Dmitri/Dropbox/Work/2013/GoLand/src/github.com/gopherjs/gopherjs/
test.017024481:1414
	          throw new Error(msg);
	                ^
	Error: runtime error: native function not implemented:
syscall.runtime_BeforeFork
	    at $callDeferred
(/Users/Dmitri/Dropbox/Work/2013/GoLand/src/github.com/gopherjs/gopherjs
/test.017024481:1414:17)
	    at $panic
(/Users/Dmitri/Dropbox/Work/2013/GoLand/src/github.com/gopherjs/gopherjs
/test.017024481:1453:3)
	    at $b (/testing/testing.go:644:5)
	    at $callDeferred
(/Users/Dmitri/Dropbox/Work/2013/GoLand/src/github.com/gopherjs/gopherjs
/test.017024481:1426:23)
	    at $panic
(/Users/Dmitri/Dropbox/Work/2013/GoLand/src/github.com/gopherjs/gopherjs
/test.017024481:1453:3)
	    at $throwRuntimeError
(/Users/Dmitri/Dropbox/Work/2013/GoLand/src/github.com/gopherjs/gopherjs
/runtime.go:31:4)
	    at $packages.syscall.runtime_BeforeFork
(/Users/Dmitri/Dropbox/Work/2013/GoLand/src/github.com/gopherjs/gopherjs
/test.017024481:4084:3)
	    at $packages.syscall.forkAndExecInChild (/syscall/exec_bsd.go:68:3)
	    at $packages.syscall.forkExec (/syscall/exec_unix.go:193:3)
	    at Object.$packages.syscall.StartProcess (FAIL	sync	1.051s